# Omikuji classifier parameters
# top_k: int
#     How many labels to return in prediction. Default 5.
# centroid_threshold: float
# Threshold for pruning label centroid vectors. Default 0
# cluster_eps: float
#   Epsilon value for determining linear classifier convergence. Default 0.0001
# cluster_k: int
#   Number of clusters. Default 2
# cluster_min_size: int
#   Labels in clusters with sizes smaller than this threshold are reassigned to other 
# clusters instead. Default 2
# cluster_unbalanced: bool
#   Perform regular k-means clustering instead of balanced k-means clustering. Default 
# False
# collapse_every_n_layers: int
#   Number of adjacent layers to collapse. This increases tree arity and decreases 
# tree depth. Default 0
# linear_c: float
#   Cost coefficient for regularizing linear classifiers. Default 1
# linear_eps
#   Epsilon value for determining linear classifier convergence. Default 0.1
# linear_loss: Literal["hinge", "log"
#   Loss function used by linear classifiers. Default hinge
# linear_max_iter: int
#   Max number of iterations for training each linear classifier. Default 20
# linear_weight_threshold: float
#   Threshold for pruning weight vectors of linear classifiers. Default 0.1
# max_depth: int
#   Maximum tree depth. Default 20
# min_branch_size: int
#   Number of labels below which no further clustering & branching is done. Default 100
# n_jobs: Optional[int
#   Number of worker threads If 0 or None, the number is selected automatically.. 
# Default None
# n_trees: int
#   Number of trees. Default 3
# check_no_labels: bool
#     Check in fit method if some samples have no labels

classifier_params:
  beam_size: 10
  centroid_threshold: 0.0
  check_no_labels: false
  cluster_balanced: false
  cluster_eps: 0.0001
  cluster_k: 4
  cluster_min_size: 1
  collapse_every_n_layers: 0
  linear_c: 1
  linear_eps: 0.1
  linear_max_iter: 20
  linear_weight_threshold: 0.1
  max_depth: 30
  min_branch_size: 10
  loss_type: log
  n_jobs: 36
  n_trees: 3
  top_k: 5

grid_search:
  verbose: 0
  n_jobs: -1

  cross_validation:
    n_folds: 5
    random_state: 42
    refit_scorer: true
  

  param_grid:
    # this represents the search grid. 
    # All other parameters are left intact and set to default
    beam_size: [10]
    cluster_balanced: [false,true]
    cluster_k: [2,3]
    linear_c: [1,5]
    max_depth: [20,30]
    n_trees: [3,4]
    top_k: [5]
    loss_type: [hinge, log]
