[tool.poetry]
name = "skomikuji"
version = "0.2.0"
description = "A Python wrapper supporting sparse input matrices for multilabel classification in extreme settings."
authors = ["Carlo Nicolini <c.nicolini@ipazia.com>"]

[tool.poetry.dependencies]
python = "^3.10"
cython = "*"
scikit-learn = "*"
pandas = "*"
scipy = "*"
tabulate = "*"
omikuji = { path = "./omikuji" }
xclib = { git = "https://github.com/kunaldahiya/pyxclib.git" }


[build-system]
requires = ["poetry-core>=1.0.0", "cython", "numpy"]
build-backend = "poetry.core.masonry.api"
